services:
  app:
    container_name: eeV
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3254:3010"
    networks:
      - eeV-network

networks:
  eeV-network:
    driver: bridge
